### ISSUE TITLE
memory control can be better.

### ISSUE THREAD

**Issue by ghost** [RamseyK/httpserver#1]
Maybe we can use share_ptr do something batter, I'm already begin now.

**Comment by RamseyK** [comment]
This was written before C++11 was widely supported so shared_ptr wasn't considered at the time. Happy to take any improvements with shared_ptr now though!

**Comment by ghost** [comment]
Yeah, you are right.
To be honest, I make a mess with language module. I using Standard C and Linux System Call to accept HTTP request; Then I using object-oriented c ( like effective c++) to  handle data; After that, I go back to using Standard C again...
